### PR TITLE
Fix for #9 - Glitchy Delete Button --plus broken test and unneeded sort

### LINKED ISSUE #9: Delete button flashes and gets all glitchy
I don't know what is causing this but I think it has to do with the timer I added that reloads the active commute's row to keep the time up to date. I think it's not getting invalidated correctly or something.

### PR DESCRIPTION
**Pull request by toastersocks**
This fixes #9 but there's also an unrelated commit that fixes a test I broke with #18 and a leftover sort in `AppManager` from #16 .
If you'd rather I submit the last commit in a separate PR since it's unrelated I can do that.
I don't think anything here touches much that's changed so far from the [customize-endpoints](/aranasaurus/CommuteLog/tree/customize-endPoints) branch but I can make the changes there instead of master and resubmit if you think it makes more sense.
Happy Halloween! 🎃

### CODE REVIEW

File: CommuteLog/CommutesViewController.swift [hunk 1]
```diff
@@ -153,5 +153,14 @@ extension CommutesViewController: UITableViewDelegate {
...
     }
+
+    func tableView(_ tableView: UITableView, willBeginEditingRowAt indexPath: IndexPath) {
+        activeCommuteTimer?.invalidate()
+        activeCommuteTimer = nil
+    }
+    
+    func tableView(_ tableView: UITableView, didEndEditingRowAt indexPath: IndexPath?) {
+        updateActiveCommuteTimer()
+        }
```
Comment (aranasaurus) [inline CommuteLog/CommutesViewController.swift]: Wayward indent here :)

**Comment by aranasaurus** [comment]
This is great, thanks :) Don't worry about the separate PR or the other branch, I still need to pull in all the other changes into it anyway.

I'll be happy to merge this after the whitespace is fixed :)  ... I need to get a linter set up and CI too.

File: CommuteLog/CommutesViewController.swift (hunk 1 above)
Comment (toastersocks) [reply CommuteLog/CommutesViewController.swift]: Ooh, nice catch

**Comment by toastersocks** [comment]
Ok, got the wonky indent fixed. 
Strangely enough, I don't think SwiftLint would have caught that one anyway. At least not without making a custom rule.
